-- k8s/sql/oracle-init.sql

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Crear usuario de aplicación
CREATE USER CASTOR_BILLING IDENTIFIED BY "Castor2025*"
  QUOTA UNLIMITED ON USERS;

-- Permisos mínimos correctos
GRANT CREATE SESSION TO CASTOR_BILLING;
GRANT CREATE TABLE TO CASTOR_BILLING;
GRANT CREATE SEQUENCE TO CASTOR_BILLING;
GRANT CREATE TRIGGER TO CASTOR_BILLING;
GRANT CREATE VIEW TO CASTOR_BILLING;
GRANT CREATE PROCEDURE TO CASTOR_BILLING;

-- Crear tabla en su propio esquema
CREATE TABLE CASTOR_BILLING.INVOICES (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    CUSTOMER_ID RAW(16) NOT NULL,
    SUBTOTAL NUMBER(18,2) NOT NULL,
    TAX NUMBER(18,2) NOT NULL,
    DISCOUNT NUMBER(18,2) NOT NULL,
    TOTAL NUMBER(18,2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
